import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_logging', 'lib_i2c', 'lib_i2s']

    bld.env.TARGET_ARCH = 'src/XR-AUDIO-216-MC.xn'
    bld.env.XSCOPE = 'src/config.xscope'

    prog = bld.program(depends_on=depends_on)


CONFIGS = {
    '768000_2_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '192000_3_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '768000_1_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '192000_3_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '192000_1_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '384000_3_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '384000_2_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '192000_2_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    'SIM': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DRECEIVE_DELAY_INCREMENT=0',
        '-DSEND_DELAY_INCREMENT=10'
    ],
    '768000_2_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '384000_4_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '384000_4_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '384000_1_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '192000_2_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '768000_4_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '768000_4_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '768000_1_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '768000_1_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '192000_4_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '192000_1_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '384000_3_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '384000_1_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '768000_3_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '384000_1_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '768000_2_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '768000_3_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '192000_4_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '384000_3_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '192000_1_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=1',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '192000_3_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '192000_2_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '768000_4_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '384000_2_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
    '384000_2_0_10': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=2',
        '-DRECEIVE_DELAY_INCREMENT=0', '-DSEND_DELAY_INCREMENT=10'
    ],
    '768000_3_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=768000', '-DNUM_I2S_LINES=3',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '192000_4_10_0': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=192000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=10', '-DSEND_DELAY_INCREMENT=0'
    ],
    '384000_4_5_5': [
        '-O2', '-report', '-g', '-DSIM=1', '-DDEBUG_PRINT_ENABLE=1',
        '-DGENERATE_MCLK', '-DSAMPLE_FREQUENCY=384000', '-DNUM_I2S_LINES=4',
        '-DRECEIVE_DELAY_INCREMENT=5', '-DSEND_DELAY_INCREMENT=5'
    ],
}

config_utils.register_configs(CONFIGS)
