import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_i2s']

    bld.env.TARGET_ARCH = 'SLICEKIT-A16'

    prog = bld.program(depends_on=depends_on)


CONFIGS = {
    'tdm': ['-O3', '-g', '-save-temps', '-DTDM'],
    'i2s': ['-O3', '-g', '-save-temps', '-DI2S'],
}

config_utils.register_configs(CONFIGS)
